spring:
  application:
    name: MiniProject
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://104.248.157.125:5434/postgres
    username: spring_minipj_g3
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

aws:
  access:
    key: AKIAYS2NW5TIFDA7LPE5
  secret:
    key: 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
  s3:
    bucket: files-upload-aws-bucket
    endpointUrl: https://files-upload-aws-bucket.s3.ap-southeast-2.amazonaws.com
  region: ap-southeast-2

server:
  port: 8080
